services:
  web:
    image: luizvinicius/bank-front-auth:1.0
    container_name: bank-front-auth
    environment:
      NODE_ENV: "production"
      NEXT_PUBLIC_BASE_URL: http://backend:8080/api/v1
    ports:
      - "3000:3000"
    networks:
      - frontend-network

networks:
  frontend-network:
    external: true
