{{- if eq .Values.strategy "bluegreen" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}-preview
spec:
  selector:
    app: {{ include "frontend.fullname" . }}
  ports:
    - port: 80
      targetPort: 3000
{{- end }}