image:
  repository: "luizvinicius/bank-front"
  tag: "1.0.2"

rollout:
  enabled: true
strategy: "bluegreen"

replicas: "1"

service:
  port: "3000"

env:
  NODE_ENV: "development"
  NEXT_PUBLIC_BASE_URL: "/api/v1"