name: Tag and release build a new version

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-release:
    if: contains(github.event.head_commit.message, 'RELEASE:')
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - name: Extract version from commit message
        id: extract_version
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          if [[ "$COMMIT_MSG" =~ RELEASE:([0-9]+\.[0-9]+(\.[0-9]+)?) ]]; then
            VERSION="${BASH_REMATCH[1]}"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "Found version: $VERSION"
          else
            echo "No RELEASE: version found in commit message"
            exit 1
          fi

  update-chart:
    runs-on: ubuntu-latest
    needs: check-release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
      
      - name: Sync main
        run: |
          git fetch origin main
          git checkout main
          git reset --hard origin/main

      - name: Update Helm Chart version
        run: |
          VERSION="${{ needs.check-release.outputs.version }}"
          echo "Atualizando Chart.yaml para vers√£o $VERSION"
          sed -i "s/^version:.*/version: $VERSION/" helm/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: \"$VERSION\"/" helm/Chart.yaml
          sed -i "s/^\(\s*tag:\s*\).*/\1\"$VERSION\"/" helm/values.yaml

      - name: Commit and push updated Chart.yaml
        env:
          REPOSITORY_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
        run: |
          VERSION="${{ needs.check-release.outputs.version }}"
          git add helm/Chart.yaml helm/values.yaml
          git commit -m "[no ci] chore: update Helm Chart version to $VERSION" || echo "Nada para commitar"
          git push origin HEAD:main

      - name: Create tag
        run: |
          VERSION="${{ needs.check-release.outputs.version }}"
          echo "Criando tag $VERSION"
          git tag $VERSION
          git push origin HEAD:main $VERSION
  build:
    runs-on: ubuntu-latest
    needs:  [check-release, update-chart]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Install dependencies (include dev)
        run: yarn install --frozen-lockfile

      - name: Build App
        run: yarn run build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bank-front:${{ needs.check-release.outputs.version }}